# TCL File Generated by Component Editor 18.1
# Mon Sep 09 23:44:48 EST 2019
# DO NOT MODIFY


# 
# direction_controller "direction_controller" v1.0
#  2019.09.09.23:44:48
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module direction_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME direction_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME direction_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL direction_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file direction_controller.sv SYSTEM_VERILOG PATH IP/IR_SENSOR/direction_controller.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point conduit_leds_array
# 
add_interface conduit_leds_array conduit end
set_interface_property conduit_leds_array associatedClock clock
set_interface_property conduit_leds_array associatedReset reset
set_interface_property conduit_leds_array ENABLED true
set_interface_property conduit_leds_array EXPORT_OF ""
set_interface_property conduit_leds_array PORT_NAME_MAP ""
set_interface_property conduit_leds_array CMSIS_SVD_VARIABLES ""
set_interface_property conduit_leds_array SVD_ADDRESS_GROUP ""

add_interface_port conduit_leds_array leds_array export Bidir 8


# 
# connection point conduit_end_left_motor
# 
add_interface conduit_end_left_motor conduit end
set_interface_property conduit_end_left_motor associatedClock clock
set_interface_property conduit_end_left_motor associatedReset reset
set_interface_property conduit_end_left_motor ENABLED true
set_interface_property conduit_end_left_motor EXPORT_OF ""
set_interface_property conduit_end_left_motor PORT_NAME_MAP ""
set_interface_property conduit_end_left_motor CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_left_motor SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_left_motor left_motor run Output 1
add_interface_port conduit_end_left_motor left_motor_speed speed Output 21


# 
# connection point conduit_end_right_motor
# 
add_interface conduit_end_right_motor conduit end
set_interface_property conduit_end_right_motor associatedClock clock
set_interface_property conduit_end_right_motor associatedReset reset
set_interface_property conduit_end_right_motor ENABLED true
set_interface_property conduit_end_right_motor EXPORT_OF ""
set_interface_property conduit_end_right_motor PORT_NAME_MAP ""
set_interface_property conduit_end_right_motor CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_right_motor SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_right_motor right_motor run Output 1
add_interface_port conduit_end_right_motor right_motor_speed speed Output 21


# 
# connection point conduit_end_led
# 
add_interface conduit_end_led conduit end
set_interface_property conduit_end_led associatedClock clock
set_interface_property conduit_end_led associatedReset reset
set_interface_property conduit_end_led ENABLED true
set_interface_property conduit_end_led EXPORT_OF ""
set_interface_property conduit_end_led PORT_NAME_MAP ""
set_interface_property conduit_end_led CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_led SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_led LED readdata Output 8

